### ISSUE TITLE
Type undefined used in Attribute ... in Entry ... is not compatible

### ISSUE THREAD

**Issue by JonathanWilbur** [JonathanWilbur/preql#2]
The problematic YAML:

```yaml
apiVersion: preql/1.0.0
kind: Entry
metadata:
  name: myself
  labels:
    name: boi
spec:
  databaseName: boofy
  structName: person
  id: 1
  distinguishedName: 'lastName=Wilbur,dc=wilbur,dc=space'
  values:
    firstName: Jonathan
    lastName: Wilbur
```

The Error:

```
Result: Failure
Exception: Error: Type 'undefined' used in Attribute 'firstname' in Entry 'myself' is not compatible with the legitimate type of that Attribute, which is a(n) 'varchar64'.
Stack: Error: Type 'undefined' used in Attribute 'firstname' in Entry 'myself' is not compatible with the legitimate type of that Attribute, which is a(n) 'varchar64'.
    at Object.keys.map.forEach (D:\home\site\wwwroot\node_modules\preql-core\dist\APIObjectKinds\Entry\kind.js:68:23)
    at Array.forEach (<anonymous>)
    at Object.validateSemantics (D:\home\site\wwwroot\node_modules\preql-core\dist\APIObjectKinds\Entry\kind.js:38:14)
    at Promise.all.k.(anonymous function).map (D:\home\site\wwwroot\node_modules\preql-core\dist\Commands\validateNamespace.js:62:21)
    at Array.map (<anonymous>)
    at Promise.all.Object.entries.map (D:\home\site\wwwroot\node_modules\preql-core\dist\Commands\validateNamespace.js:58:10)
    at Array.map (<anonymous>)
    at Object.validateNamespace (D:\home\site\wwwroot\node_modules\preql-core\dist\Commands\validateNamespace.js:56:10)
    at Object.<anonymous> (D:\home\site\wwwroot\dist\Configure\index.js:60:21)
    at Generator.next (<anonymous>)
```

The problem is that the `values` keys are lower-cased, then later used to look up the values from `values`. For instance, if `values` has a key `firstName`, it gets lower-cased to `firstname`. Later on `values`.`firstname` is accessed, rather than `values.firstName`, which is `undefined`.
